/*
 * This source file was generated by the Gradle 'init' task
 */
package opencv.gradle.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        // App classUnderTest = new App();
        assertTrue(true);
    }
}
